
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

ignored = [
    "github.com/docker/docker/errdefs",
    "github.com/docker/docker/pkg/archive",
    "github.com/docker/docker/pkg/fileutils",
    "github.com/docker/docker/pkg/homedir",
    "github.com/docker/docker/pkg/idtools",
    "github.com/docker/docker/pkg/ioutils",
    "github.com/docker/docker/pkg/jsonmessage",
    "github.com/docker/docker/pkg/longpath",
    "github.com/docker/docker/pkg/mount",
    "github.com/docker/docker/pkg/pools",
    "github.com/docker/docker/pkg/progress",
    "github.com/docker/docker/pkg/streamformatter",
    "github.com/docker/docker/pkg/stringid",
    "github.com/docker/docker/pkg/system",
    "github.com/docker/docker/pkg/tarsum",
    "github.com/docker/docker/pkg/term",
    "github.com/docker/docker/pkg/term/windows",
    "github.com/docker/docker/registry",
    "github.com/docker/docker/registry/resumable",
    "github.com/docker/cli/cli",
    "github.com/docker/go-metrics",
    "github.com/docker/distribution/manifest",
    "github.com/docker/distribution/manifest/manifestlist",
    "github.com/docker/distribution/manifest/schema2",
    "github.com/docker/distribution/metrics",
    "github.com/docker/distribution/registry/*",
    "github.com/docker/distribution/uuid",
    "github.com/docker/cli/cli/manifest",
    "github.com/docker/cli/cli/command/*",
    "github.com/docker/cli/cli/compose/*",
    "github.com/docker/swarmkit/manager/raftselector",
    "github.com/docker/swarmkit/protobuf/plugin"
  ]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/chzyer/readline"
  revision = "c914be64f07d9998f52bf0d598ec26d457168c0f"

[[constraint]]
  name = "github.com/docker/docker"
  revision = "641e2c01cca0c9c66b173a52c1f1ef12a934dfa9"

[[constraint]]
  name = "github.com/docker/go-connections"
  branch = "master"

[[constraint]]
  name = "github.com/docker/go-units"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/gizak/termui"

[[constraint]]
  name = "github.com/gosuri/uitable"
  revision = "62e40473eadf9579716227a0033cd8db16e1c500"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  revision = "fc93116606d0a71d7e9de0ad5734fdb4b8eae834"

[[constraint]]
  name = "github.com/mattn/go-runewidth"
  revision = "12e0ff74603c9a3209d8bf84f8ab349fe1ad9477"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  revision = "756f7b183b7ab78acdbbee5c7f392838ed459dda"

[[constraint]]
  name = "github.com/mitchellh/go-wordwrap"
  revision = "ad45545899c7b13c020ea92b2072220eefad42b8"

[[constraint]]
  branch = "master"
  name = "github.com/nsf/termbox-go"

[[constraint]]
  name = "github.com/olekukonko/tablewriter"
  revision = "cca8bbc0798408af109aaaa239cbd2634846b340"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "2.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  revision = "494e70f7620561491c2ca11e185bbef4b70060da"

[[override]]
  name = "github.com/docker/libnetwork"
  revision = "0ae9b6f38f24f65567d4b46602502b33c95cf57a"

[[constraint]]
  branch = "master"
  name = "github.com/maxzender/jv"

  
