name: dry
version: git
summary: A Docker manager for the terminal
description: |
  Dry is a terminal application to manage Docker and Docker Swarm.
  It shows information about Containers, Images, Networks, Volumes,
  and Compose projects. If running a Docker Swarm, it can manage
  Nodes, Services, and Stacks. It can be used with both local and
  remote Docker daemons.
base: core24

grade: stable
confinement: strict

apps:
  dry:
    command: bin/dry

parts:
  dry:
    source-type: git
    source: https://github.com/moncho/dry
    plugin: go
    build-snaps:
      - go/1.26/stable
